import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, Auth } from 'firebase/auth';
import { getFirestore, enableIndexedDbPersistence, Firestore } from 'firebase/firestore';

// Note: firebase-applet-config.json is generated by the set_up_firebase tool.
// We use dynamic imports or check for existence to prevent build/runtime crashes.

let app: FirebaseApp | null = null;
let auth: Auth | null = null;
let db: Firestore | null = null;

const getFirebaseConfig = async () => {
  try {
    // @ts-ignore - this file might not exist yet
    const config = await import('../../firebase-applet-config.json');
    return config.default || config;
  } catch (e) {
    console.warn("Firebase configuration not found. Please complete the setup in the prompt.");
    return null;
  }
};

export const getFirebaseApp = async () => {
  if (getApps().length) return getApp();
  
  const config = await getFirebaseConfig();
  if (!config || !config.apiKey) {
    throw new Error('Firebase is not configured. Please click "Accept" in the Firebase setup UI.');
  }
  
  app = initializeApp(config);
  return app;
};

export const getFirebaseAuth = async () => {
  if (auth) return auth;
  const app = await getFirebaseApp();
  auth = getAuth(app);
  return auth;
};

export const getFirebaseDb = async () => {
  if (db) return db;
  const app = await getFirebaseApp();
  const config = await getFirebaseConfig();
  db = getFirestore(app, config.firestoreDatabaseId);

  // Enable offline persistence
  if (typeof window !== 'undefined') {
    enableIndexedDbPersistence(db).catch((err) => {
      console.warn("Persistence error:", err.code);
    });
  }
  return db;
};

export const googleProvider = new GoogleAuthProvider();

export const signInWithGoogle = async () => {
  try {
    const auth = await getFirebaseAuth();
    const result = await signInWithPopup(auth, googleProvider);
    return result.user;
  } catch (error) {
    console.error("Auth error:", error);
    throw error;
  }
};

export const logout = async () => {
  const auth = await getFirebaseAuth();
  return signOut(auth);
};

// For simpler usage in components, we can export the instance getters
// Or if you prefer the previous style, you'd have to handle the async nature.
// However, standard React patterns use hooks or initialization in useEffect.
